# TrueNAS/FreeNAS Integration Configuration
truenas:
  host: truenas.local
  protocol: https
  port: 443
  verify_ssl: false
  
sync:
  enabled: true
  interval: 300  # 5 minutes
  datasets:
    - name: gentleman/models
      local_path: /data/models
      sync_direction: bidirectional
    - name: gentleman/media
      local_path: /media
      sync_direction: pull
    - name: gentleman/backups
      local_path: /backups
      sync_direction: push

backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 30  # days
  compression: gzip
  
monitoring:
  enabled: true
  metrics:
    - disk_usage
    - pool_health
    - dataset_snapshots
    - replication_status
