# 🎩 Gentleman I7 Node - M1 Lighthouse Connection
pki:
  ca: ca.crt
  cert: i7-node.crt
  key: i7-node.key

static_host_map:
  "192.168.100.1": ["192.168.68.111:4243"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 0

punchy:
  punch: true
  respond: true
  delay: 1s

tun:
  disabled: false
  dev: nebula1
  mtu: 1300

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 22
      proto: tcp
      host: any
    - port: 8000-8010
      proto: tcp
      host: any
      groups:
        - audio-services
        - clients
        - monitoring
    - port: 4242
      proto: udp
      host: any
